# language setting
language: java

# jdk tag
jdk:
 - oraclejdk8

# include
branches:
  only:
    - master

# notify
notifications:
     email:
         recipients:
             - develop@schlegel11.de
