# language setting
language: java

# build systems
os:
  - linux
  - osx

# workaround for osx builds
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then "wget --no-cookies --no-check-certificate --header \"Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie\" http://download.oracle.com/otn-pub/java/jdk/8u66-b17/jdk-8u66-macosx-x64.dmg"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil mount jdk-8u66-macosx-x64.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg /Volumes/JDK\ 8\ Update\ 66/JDK\ 8\ Update\ 66.pkg -target LocalSystem; fi

# jdk tag
jdk:
 - oraclejdk8

# include
branches:
  only:
    - master

# notify
notifications:
     email:
         recipients:
             - develop@schlegel11.de
